Algoritmo "Area do RETÂNGULO"
// Disciplina   : JavaScript
// Professor   : Jailson
// Descrição   :
// Autor(a)    : Marcus V
// Data atual  : 31/08/2022
Var
// Seção de Declarações das variáveis 
base: inteiro
altura: inteiro
total: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a base")
leia(base)

escreval("Digite a altura")
leia(altura)

total<-base*altura
escreval("O resultado será", total)
Fimalgoritmo

