Algoritmo "Area o raio"
// Disciplina   : JavaScript
// Professor   : Jailson
// Descrição   :
// Autor(a)    : Marcus V
// Data atual  : 31/08/2022
Var
// Seção de Declarações das variáveis
raio: inteiro
total: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite o raio")
leia(raio)

total<-3.14*(raio*raio)
escreval("O resultado será", total)
Fimalgoritmo

