Algoritmo "Área do quadrado"
// Disciplina:  JavaScript
// Professor   : Jailson
// Descrição   :
// Autor(a)    : Marcus V
// Data atual  : 31/08/2022
Var
// Seção de Declarações das variáveis
lado: inteiro
total: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite o lado")
leia(lado)
total<-lado*lado
escreval("O resultado será", total)
Fimalgoritmo

